# Adapted from https://gist.github.com/y0ssar1an/df2dab474520c4086926f672c52db139
language: go

go:
  - 1.11.x
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

notifications:
  email: false

env:
  - GO111MODULE=on

install:
  - go mod download

script:
  - go test -v -race ./...     # Run all the tests with the race detector enabled
  - go vet ./...               # go vet is the official Go static analyzer
