language: go
go:
- 1.10.x
- 1.11.x
- master
matrix:
  allow_failures:
  - go: master
  fast_finish: true
notifications:
  email: false
env:
- GO111MODULE="on"
script:
- go build -v
- go test -v -race ./...
- go vet ./...
before_install:
- openssl aes-256-cbc -K $encrypted_1d073d5eb2c7_key -iv $encrypted_1d073d5eb2c7_iv
  -in scripts/artifactory.lic.enc -out scripts/artifactory.lic -d
